spring:
  redis:
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    host: 47.114.157.175
    port: 6379
    lettuce: # netty 线程安全的reids客户端
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
    timeout: 10000 # 连接超时(ms)
    password: 123456
server:
  port: 2233